//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ProductSold
    {
        public int Id { get; set; }
         [DisplayName("Product Name")]
        public Nullable<int> ProductId { get; set; }
        [DisplayName("Customer Name")]
        public Nullable<int> CustomerId { get; set; }
        [DisplayName("Store Name")]
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
